### ISSUE TITLE
How can I install Types?

### ISSUE THREAD

**Issue by Achalogy** [hlhr202/llama-node#13]
I got a lot of error messages like this one:

Cannot find module 'llama-node/dist/llm/llama-rs' or its corresponding type declarations.

How can I install the types?

**Comment by hlhr202** [comment]
hi, not sure which version did you install? I tried version 0.0.21, the type definition is working actually.

![image](https://user-images.githubusercontent.com/2355528/231520250-ca83ed21-e0a5-4ef7-91fe-f74cf2ccbbd7.png)

**Comment by Achalogy** [comment]
Me too, I have 0.0.21 versión :( Maybe some config file(?

tsconfig.json
```json
{
  "compilerOptions": {
    "outDir": "./dist",
    "target": "es2022",
    "module": "nodenext",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "types": ["node"]
  },
  "include": ["./"]
}
```

**Comment by Achalogy** [comment]
Changed "module": "nodenext" to "module": "CommonJS". And it worked.

**Comment by Achalogy** [comment]
Can you show me what tsconfig.ts do you use? I still getting errors because tsc change commonjs imports to ES.

**Comment by hlhr202** [comment]
https://github.com/hlhr202/llama-node/tree/main/example

Updated full examples here.
