### ISSUE TITLE
tsx: not found while running npm install

### ISSUE THREAD

**Issue by jonit-dev** [hlhr202/llama-node#9]
Hi there! Nice package.

I'm trying to install this in a brand project, but I'm facing this issue

```
npm ERR! code 127
npm ERR! path /MYPATHHERE/node_modules/@llama-node/core
npm ERR! command failed
npm ERR! command sh -c -- tsx scripts/build.ts
npm ERR! sh: 1: tsx: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jonit/.npm/_logs/2023-04-07T01_54_20_183Z-debug-0.log
``` 

Any toughts?

Is it a typo?

Shouldn't it be **tsc** scripts/build.ts?

**Comment by hlhr202** [comment]
> 

will fix asap

**Comment by hlhr202** [comment]
@jonit-dev can help me check if 0.0.17 solved this?

**Comment by hlhr202** [comment]
fixed in https://github.com/hlhr202/llama-node/releases/tag/v0.0.17
